version = 1

test_patterns = ["src/**/tests/**"]

exclude_patterns = ["examples/**, docs/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]
  dialect = "typescript"
  module_system = "es-modules"
